[package]
name = "uam-control-system-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.93"
serde = { version = "1.0.130", features = ["derive"] }
serde-wasm-bindgen = "0.6.5"
